### ISSUE TITLE
Dont show data from db

### ISSUE THREAD

**Issue by Peldano-pb** [abeauseigle/webSqlApp#7]
I change the parameters to use this example with another database. The data is sended to the server, but i cant the sync data. Do you have some fast example to check data sync and show the data?

**Comment by abeauseigle** [comment]
Hi Peldano-pb, The best way I found is to run the php code (Bypass the authentication) to verify if you receive a good server answer. It will allow you to see if you have a SQL error. If the answer is OK, usually it's because the database fields are not the same server side and client side. Hope it gonna help.

**Comment by Peldano-pb** [comment]
It helped me a lot, the answer was OK and the sync was good, but the sync was being incomplete because the new elements didnt got removed and i get duplicate data when i send the new fields to the server. Anyway, i find a way to solve this and the app is running like i want.

Thanks!

**Comment by abeauseigle** [comment]
See the new WebSqlSync in the TodoApp2 (new improved bidirectional sync and app).
